name: Deploy static content to Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Add a build step if your project requires it
      - name: Install dependencies
        run: npm install  # Or yarn install, pip install, etc.

      - name: Build project
        run: npm run build  # Or your build command (e.g., hugo, next build)

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload only the built files (e.g., build/, dist/, public/)
          path: 'build/'  # Update this to match your build output directory

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
